[package]
name = "server"
version = "0.0.1"
authors = ["logicfan"]
edition = "2021"

[dependencies]
actix-web = "4.9"
actix-files = "0.6"
serde = { version = "*", features = ["derive"] }
rand = "0.8"
rsa = "0.9"
sha2 = "0.10"
hmac = "0.12"
jwt = "0.16"
polodb_core = "5.1"
log = "0.4"
derive_more = { version = "1.0", features = ["display", "from"] }
const_format = "0.2"
